server:
  port: 8070
spring:
    datasource:
      url: jdbc:h2:mem:cards
      driver-class-name: org.h2.Driver
      username: sa
      password: ""
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
    config:
      import:
        - "application_qa.yaml"
        - "application_prod.yaml"
    profiles:
      active: "card_qa"



build:
  version: "1.0"

cards:
  message: "Welcome to EAZYBANK cards related to local APIs"
  contactDetails:
    name: "Houn Lyhour - Software Engineering"
    email: "lhour@gmail.com"
  onSupportCall:
    - (111) 321-1234
    - (111) 325-1254