server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:loans
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yaml"
      - "application_prod.yaml"
  profiles:
    active: "qas"

build:
  version: "3.2"

loans:
  message: "Welcome to EAZYBANK loans related to local APIs"
  contactDetails:
    name: "JING - Full Stack Developer"
    email: "jing@gmail.com"
  onCallSupport:
    - (333) 321-1234
    - (333) 325-1254