spring:
  config:
    activate:
      on-profile: "loan_prod"

build:
  version: "1.2"

loans:
  message: "Welcome to EAZYBANK loans related to PROD APIs"
  contactDetails:
    name: "JING - Product Owner"
    email: "jing@gmail.com"
  onCallSupport:
    - (333) 321-1234
    - (333) 325-1254