server:
  port: 8761

spring:
  application:
    name: "eurekaserver"

  config:
    import: "optional:configserver:http://localhost:8072/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    com:
      jing:
        eurekaserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"