build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related PROD APIs"
  contactDetails:
    name: "niza Doe - Developer"
    email: "youn@gmail.com"
  onCallSupport:
    -(777) 777-2264
    -(777) 777-2855