build:
  version: "2.0"

cards:
  message: "Welcome to EAZYBANK cards related to PROD APIs"
  contactDetails:
    name: "JING - Product Owner"
    email: "jing@gmail.com"
  onSupportCall:
    - (222) 321-1234
    - (222) 325-1254