build:
  version: "1.1"

cards:
  message: "Welcome to EAZYBANK cards related to QA APIs"
  contactDetails:
    name: "JING - QA Testing"
    email: "jing@gmail.com"
  onSupportCall:
    - (333) 321-1234
    - (333) 325-1254