build:
  version: "1.2"

loans:
  message: "Welcome to EAZYBANK loans related to QA APIs"
  contactDetails:
    name: "JING - QA Testing"
    email: "jing@gmail.com"
  onCallSupport:
    - (333) 321-1234
    - (333) 325-1254