services:
  network-deploy-services:
    networks:
      - eazybank

  microserivce-db-congig:
    extends:
      service: network-deploy-services
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $${POSTGRES_DB}"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  microserivce-base-config:
    extends:
      service: network-deploy-services
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"

  microservice-configserver-config:
    extends:
      service: microserivce-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8072/

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/