spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/Lyhour-Houn12/eazybank-config-repo.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        monitor:
#          validation-filter-enabled: false
#    bus:
#      enabled: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true



encrypt:
  key: "21GDJAKLGASEWDA3214123DAKLDJARWAWDLJAEW1231"

server:
  port: 8072

